version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker Image
          command: docker build -t Babrov/docker-react -f Dockerfile.dev .

      - run:
          name: Run Tests
          command: docker run -e CI=true Babrov/docker-react npm run test -- --coverage
